### ISSUE TITLE
Install python-pdal

### ISSUE THREAD

**Issue by SmithB** [snowex-hackweek/docker-image#10]
This is a long shot (it hasn't worked in other contexts) but would you mind installing pdal-python?  If it works, it would be nice to include in the lidar tutorial (OTW we'll just call the command-line version)

**Comment by scottyhq** [comment]
> This is a long shot (it hasn't worked in other contexts) but would you mind installing pdal-python? 

How do you usually install this? 

If I understand correctly `conda install pdal` (https://github.com/snowex-hackweek/docker-image/pull/9) only installs the command line tool?

**Comment by SmithB** [comment]
My bad.  the package is called python-pdal.

**Comment by scottyhq** [comment]
closed by #11

**Comment by SmithB** [comment]
Unfortunately, that doesn't seem to have installed the bindings:
import pdal
gives:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-58-3ef3d679e24d> in <module>
----> 1 import pdal

/srv/conda/envs/notebook/lib/python3.8/site-packages/pdal/__init__.py in <module>
      1 __version__='2.4.0'
      2 
----> 3 from .pipeline import Pipeline
      4 from .array import Array
      5 from .dimension import dimensions

/srv/conda/envs/notebook/lib/python3.8/site-packages/pdal/pipeline.py in <module>
      1 
----> 2 from pdal import libpdalpython
      3 import numpy as np
      4 
      5 class Pipeline(object):

ImportError: libpdal_base.so.13: cannot open shared object file: No such file or directory

**Comment by scottyhq** [comment]
> ImportError: libpdal_base.so.13: cannot open shared object file: No such file or directory 

Seems necessary to pin minor versions: https://github.com/PDAL/python/issues/84

**Comment by scottyhq** [comment]
hopefully closed by #12
