### ISSUE TITLE
Add 'pycrs' to list of conda packages

### ISSUE THREAD

**Issue by jomey** [snowex-hackweek/docker-image#26]
Needed for the lidar ASO tutorial and currently missing

**Comment by dshean** [comment]
Maybe we can just use `pyproj` for this functionality?

**Comment by jomey** [comment]
I would leave that decision up to the author of the tutorial to see if that is suitable.

**Comment by dshean** [comment]
Looks like only used here:`pycrs.parse.from_epsg_code(epsg_code).to_proj4()` in Clipping Rasters section https://snowex-hackweek.github.io/website/tutorials/lidar/ASO_data_tutorial.html#clipping-rasters.

Should be able to accomplish same thing with `pyproj.CRS.from_epsg(epsg_code).to_proj4()`

Though I'm not sure that we actually need to convert to a proj string here, as rasterio should be able to handle EPSG codes directly: https://rasterio.readthedocs.io/en/latest/api/rasterio.crs.html

@c-webster, maybe you can tweak your notebook?  I could also be missing some justification on the need for pycrs here.

**Comment by jomey** [comment]
Looks like we figured this one out and there will be an update to the notebook.
